title: SI
lang: es
description: Sistemas Informáticos (1ºSI)

remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs

translate:
 previous: Anterior
 Next: Siguiente
 note: info
 search: buscar
 search_docs: buscar..
 searching: buscando
 not_found: No encontrado
 search_results_found: Resultados Encontrados
 this: este
 is_under_the_terms_of: esta_bajo_los_terminos_de

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

